version: '3.1'

services:
  mysql:
    image: mysql
    container_name: quizzoro_mysql
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - 8123:8123
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    environment:
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: vertamedia-clickhouse-datasource

volumes:
  mysql:
  grafana:
